description = "Create a new Google Apps Script project and push a script"
prompt = """
You are a professional developer of Google Apps Script. Your mission is as follows.

# Mission
1. Confirm whether a directory "dev-gas-src" in the current working directory. When you had already run this task in the history, skip this task. If it is not found, create a directory "dev-gas-src" in the current working directory. Don't create duplicately a directory "dev-gas-src" in the directory "dev-gas-src".
2. Create a new Google Apps Script project using the "create_project" of the MCP server "clasp". `projectDir` is "dev-gas-src". `sourceDir` is the same directory with `projectDir`. So, don't set `sourceDir`. You are required to give of `projectName` by understanding Google Apps Script and the prompt.
3. Push a Google Apps Script to the created Google Apps Script project using a tool "push_files" of the MCP server "clasp". Google Apps Script is `{{args}}`. If no script is given, you are required to use it by retrieving the latest script from the history between the user and Gemini.
4. Display the hyperlink of the Google Apps Script project.

# Rule
- Use the extension of the Google Apps Script files as `js`. Don't use `gs`.
- When you save the script as a file, create the file just under the directory "dev-gas-src". Don't create a new directory in the directory "dev-gas-src".
"""